server:
  port: 8081
spring:
  application:
    name: storage
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.2.88:3306/storage?userSSL=false&useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        druid:
          initial-size: 5
          max-active: 100
          min-idle: 10
          max-wait: 60000
          keep-alive: true
    sharding:
      tables:
        storage_tbl:
          actual-data-nodes: ds.storage_tbl_$->{0..1}
          table-strategy:
            inline:
              sharding-column: commodity_code
              algorithm-expression: storage_tbl_$->{commodity_code % 2}
    defaultDataSourceName: ds
    props:
      sql:
        show: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.2.88:3306/storage?userSSL=false&useUnicode=true&characterEncoding=UTF8
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl